[project]
name = "slack-qa-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.41",
    "ruff>=0.12.0",
    "slack-sdk>=3.35.0",
]
